#!/usr/bin/env python3
"""Inline every asset into one file that works anywhere.

`web/index.html` references its engraving and its fonts as sibling files, which
is right for a deployment: the browser caches them separately and a new report
does not re-download 176 KB of fonts. But it means the file alone is not the
page. Opened without its `assets/` folder, the plate, the watermark and the
type all disappear.

This writes `web/jastrow-standalone.html`, the same page with the engraving and
the fonts inlined as data URIs. One file, no folder, no server: mail it, drop
it in a preview pane, open it from a USB stick.

    python3 scripts/bundle.py

It is generated, not edited. Deploy `web/` as it is and treat the standalone as
something to hand to a person rather than to a server.
"""

from __future__ import annotations

import base64
import pathlib
import re
import sys

_ROOT = pathlib.Path(__file__).resolve().parents[1]
WEB = _ROOT / "web"
SOURCE = WEB / "index.html"
TARGET = WEB / "jastrow-standalone.html"

MEDIA = {
    ".webp": "image/webp",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".woff2": "font/woff2",
}


def data_uri(relative: str) -> str:
    path = WEB / relative
    if not path.exists():
        raise SystemExit("missing asset: " + relative)
    media = MEDIA.get(path.suffix)
    if media is None:
        raise SystemExit("no media type known for " + relative)
    return "data:" + media + ";base64," + base64.b64encode(path.read_bytes()).decode("ascii")


def main() -> int:
    page = SOURCE.read_text()

    # Preloads are pointless once the bytes are in the document, and under
    # file:// they log failures that look like real ones.
    page = re.sub(r'\n<link rel="preload"[^>]*>', "", page)

    # The social card and the icons are not part of what the page draws. A
    # scraper cannot use a data URI in og:image anyway, and inlining the card
    # alone would have tripled the file.
    skip = ("assets/og-card.png", "assets/favicon-32.png", "assets/favicon-180.png",
            "assets/favicon-512.png")

    inlined = []
    for match in sorted(set(re.findall(r'assets/[A-Za-z0-9_./-]+', page))):
        if match in skip:
            continue
        page = page.replace(match, data_uri(match))
        inlined.append(match)

    # The social card and the icons stay as links: a data URI in og:image is
    # useless to a scraper, and a bundled file is not the thing being scraped.
    page = page.replace(
        "<title>Jastrow - divergence report</title>",
        "<title>Jastrow - divergence report</title>\n"
        "<!-- Generated by scripts/bundle.py. Edit web/index.html instead. -->",
    )

    TARGET.write_text(page)
    size = TARGET.stat().st_size

    print("wrote " + str(TARGET.relative_to(_ROOT)) + "  " + str(round(size / 1024)) + " KB")
    for name in inlined:
        print("  inlined " + name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
